language: node_js
node_js:
- '0.10'
env:
  global:
env:
  global:
    - secure: IB1KrST0in2OcmUt61B8QZdxgVK46phR4V549+yQgpEiES+ru6rau82FxR5H3JLWF4o+t8Q7lB25TfzNCFYCVD2NEvlsSXJKCWcyXojJim4jJ3pzV5B6hib50W4CjnGtKo1lwSLLjw2ujiGKXWFA1IMR0+UerW5TLaYxTj1M3/lGk0cqDDmR9/uI9ALFlhKShMdGWCASkaVBlw9B/479ClIWol/JUWyKdusHQ2ZfwX+WxElHKm4kLtA6Kzp5m2u96GSYVtLKyp80yJ9yAFOSSZnhya67tykwd/2u8eUQq1MNlkLkRrvXZnNt0Za7iXJwqtrpPNoulICFmTmwOCAF5VKdkEtQoGWFRCWGYN1SRmzpHseVhVAKhsfD5VT/SCKznA01UuBTA0oqH/Fn3NUNn8PyNegc11HwjQ5Cf6QK6Ey0J7kPfsLnyLpAH0xcJanh6a9Mvk6PE6lWYJn6DyfEyiPZUSf4L8Sgz/isvGeVGF19yelG5lkYAv0JVuDILGcQAyY/yKKSAsPoNu5/izeMuylOfa4A/a49wvaefo1a9D2twhnbgVBQA1YNGwB6nCdxfSGc1XHRfsxKwJxnYMQ1ldFi9NHtrc+NKqhWhaf7T62mbQ4LunvZ2JasLvGIebbiOpUk1ApG+QAj+Y6Qhtefi5r9o00b7nYRDELHaSZVQyc=
    - secure: Du+y8sRmxrNUngTwcjMcI7X4GUgOUTiq6R4+yKafpEKMy7m6Vv2RpI3EoqveB7J4z6sSM5ck7IbZ+WvXEBdNalVhvltvwOrbCXfyxzvnBnA/rCEDjesN6uZ/vJjkPtN8VshZYzWjpwmdHuVuM1KId8BFm2LNsVCyjVLZLdSoL6tc67HLoL2szt+cOQUjFfwMBM4UauqokJv05mYp4BW+17KO0AzblzyF4SWxnU+69Q66m/+Lju6/VAzPfw4l+J5BDqEXYCM3ofcYXPaIcDdlgyoTaWN0XfNb2lmLwFuTezcyZwsCEUTxg18SiNZ2ijHLXoNUcdE8vB97rBYH3nRFNVwTVYcQ0kNhIBQv46Ckb9N8S3StULaZTm3OuQ+0QPsui9B+vKyVEoNr3Fix0qvPvLMLCB3rAu1a/i2rk0vEozQC8u5wdhl4qf+iOXNKLxvr2fLD7JuUD4Pak2HAQ6FayAUSt3Uam7b1knb0ZJYecsruErKxnrZrjkGP+tMRPTOku3NJElr9ufL7EeM5iQRhbLHfHvUv/07zJWhdC7g3iu87/KWBsKp7wAu242v9fK9iiqwZs0CkuU9VvJVZfJt1+R6K5RPQnWC3S1UgaJeg1xWUq0bludMBEb3tSqCDGHgRSXIBN4QDC83VrED0ZjzbEznRdbOj3XkGlVjaYiBMnAM=
branches:
  only:
  - master
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g karma
- bower install
- npm install
- npm run build
